name: cryptor
description: "A new Flutter project."
publish_to: 'none' # flutter run -d macos


version: 1.0.2+4

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  csv: ^6.0.0
  crypto: ^3.0.6
  file_picker: ^8.1.3
  file_saver: ^0.2.14
  clipboard: ^0.1.3

  # Network
  dio: ^5.7.0
  mailto: ^2.0.0
  intl: ^0.19.0
  get: ^4.6.6
  get_storage: ^2.1.1

  flutter_svg: ^2.0.11
  google_fonts: ^6.2.1
  neon_circular_timer: ^0.0.8

  encrypt: ^5.0.3
  pointycastle: ^3.9.1

  flutter_markdown: ^0.7.4+1
  path_provider: ^2.1.5
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

  flutter_localizations:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/footer.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  #  dart run flutter_launcher_icons
  image_path_android: "assets/main-logo.jpg"
  image_path_ios: "assets/main-logo.jpg"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#f5f6f9"
  web:
    generate: true
    image_path: "assets/main-logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/main-logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/main-logo.jpg"